<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\TTSLanguage;
use Illuminate\Database\Seeder;

final class TTSLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = [
            'Afrikaans (South Africa)' => 'af-ZA',
            'Amharic (Ethiopia)' => 'am-ET',
            'Arabic (United Arab Emirates)' => 'ar-AE',
            'Arabic (Bahrain)' => 'ar-BH',
            'Arabic (Algeria)' => 'ar-DZ',
            'Arabic (Egypt)' => 'ar-EG',
            'Arabic (Iraq)' => 'ar-IQ',
            'Arabic (Jordan)' => 'ar-JO',
            'Arabic (Kuwait)' => 'ar-KW',
            'Arabic (Lebanon)' => 'ar-LB',
            'Arabic (Libya)' => 'ar-LY',
            'Arabic (Morocco)' => 'ar-MA',
            'Arabic (Oman)' => 'ar-OM',
            'Arabic (Qatar)' => 'ar-QA',
            'Arabic (Saudi Arabia)' => 'ar-SA',
            'Arabic (Syria)' => 'ar-SY',
            'Arabic (Tunisia)' => 'ar-TN',
            'Arabic (Yemen)' => 'ar-YE',
            'Assamese (India)' => 'as-IN',
            'Azerbaijani (Latin, Azerbaijan)' => 'az-AZ',
            'Bulgarian (Bulgaria)' => 'bg-BG',
            'Bangla (Bangladesh)' => 'bn-BD',
            'Bengali (India)' => 'bn-IN',
            'Bosnian (Bosnia and Herzegovina)' => 'bs-BA',
            'Catalan' => 'ca-ES',
            'Czech (Czechia)' => 'cs-CZ',
            'Welsh (United Kingdom)' => 'cy-GB',
            'Danish (Denmark)' => 'da-DK',
            'German (Austria)' => 'de-AT',
            'German (Switzerland)' => 'de-CH',
            'German (Germany)' => 'de-DE',
            'Greek (Greece)' => 'el-GR',
            'English (Australia)' => 'en-AU',
            'English (Canada)' => 'en-CA',
            'English (United Kingdom)' => 'en-GB',
            'English (Hong Kong SAR)' => 'en-HK',
            'English (Ireland)' => 'en-IE',
            'English (India)' => 'en-IN',
            'English (Kenya)' => 'en-KE',
            'English (Nigeria)' => 'en-NG',
            'English (New Zealand)' => 'en-NZ',
            'English (Philippines)' => 'en-PH',
            'English (Singapore)' => 'en-SG',
            'English (Tanzania)' => 'en-TZ',
            'English (United States)' => 'en-US',
            'English (South Africa)' => 'en-ZA',
            'Spanish (Argentina)' => 'es-AR',
            'Spanish (Bolivia)' => 'es-BO',
            'Spanish (Chile)' => 'es-CL',
            'Spanish (Colombia)' => 'es-CO',
            'Spanish (Costa Rica)' => 'es-CR',
            'Spanish (Cuba)' => 'es-CU',
            'Spanish (Dominican Republic)' => 'es-DO',
            'Spanish (Ecuador)' => 'es-EC',
            'Spanish (Spain)' => 'es-ES',
            'Spanish (Equatorial Guinea)' => 'es-GQ',
            'Spanish (Guatemala)' => 'es-GT',
            'Spanish (Honduras)' => 'es-HN',
            'Spanish (Mexico)' => 'es-MX',
            'Spanish (Nicaragua)' => 'es-NI',
            'Spanish (Panama)' => 'es-PA',
            'Spanish (Peru)' => 'es-PE',
            'Spanish (Puerto Rico)' => 'es-PR',
            'Spanish (Paraguay)' => 'es-PY',
            'Spanish (El Salvador)' => 'es-SV',
            'Spanish (United States)' => 'es-US',
            'Spanish (Uruguay)' => 'es-UY',
            'Spanish (Venezuela)' => 'es-VE',
            'Estonian (Estonia)' => 'et-EE',
            'Basque' => 'eu-ES',
            'Persian (Iran)' => 'fa-IR',
            'Finnish (Finland)' => 'fi-FI',
            'Filipino (Philippines)' => 'fil-PH',
            'French (Belgium)' => 'fr-BE',
            'French (Canada)' => 'fr-CA',
            'French (Switzerland)' => 'fr-CH',
            'French (France)' => 'fr-FR',
            'Irish (Ireland)' => 'ga-IE',
            'Galician' => 'gl-ES',
            'Gujarati (India)' => 'gu-IN',
            'Hebrew (Israel)' => 'he-IL',
            'Hindi (India)' => 'hi-IN',
            'Croatian (Croatia)' => 'hr-HR',
            'Hungarian (Hungary)' => 'hu-HU',
            'Armenian (Armenia)' => 'hy-AM',
            'Indonesian (Indonesia)' => 'id-ID',
            'Icelandic (Iceland)' => 'is-IS',
            'Italian (Italy)' => 'it-IT',
            'Inuktitut (Syllabics, Canada)' => 'iu-CANS-CA',
            'Inuktitut (Latin, Canada)' => 'iu-LATN-CA',
            'Japanese (Japan)' => 'ja-JP',
            'Javanese (Latin, Indonesia)' => 'jv-ID',
            'Georgian (Georgia)' => 'ka-GE',
            'Kazakh (Kazakhstan)' => 'kk-KZ',
            'Khmer (Cambodia)' => 'km-KH',
            'Kannada (India)' => 'kn-IN',
            'Korean (Korea)' => 'ko-KR',
            'Lao (Laos)' => 'lo-LA',
            'Lithuanian (Lithuania)' => 'lt-LT',
            'Latvian (Latvia)' => 'lv-LV',
            'Macedonian (North Macedonia)' => 'mk-MK',
            'Malayalam (India)' => 'ml-IN',
            'Mongolian (Mongolia)' => 'mn-MN',
            'Marathi (India)' => 'mr-IN',
            'Malay (Malaysia)' => 'ms-MY',
            'Maltese (Malta)' => 'mt-MT',
            'Burmese (Myanmar)' => 'my-MM',
            'Norwegian Bokmål (Norway)' => 'nb-NO',
            'Nepali (Nepal)' => 'ne-NP',
            'Dutch (Belgium)' => 'nl-BE',
            'Dutch (Netherlands)' => 'nl-NL',
            'Odia (India)' => 'or-IN',
            'Punjabi (India)' => 'pa-IN',
            'Polish (Poland)' => 'pl-PL',
            'Pashto (Afghanistan)' => 'ps-AF',
            'Portuguese (Brazil)' => 'pt-BR',
            'Portuguese (Portugal)' => 'pt-PT',
            'Romanian (Romania)' => 'ro-RO',
            'Russian (Russia)' => 'ru-RU',
            'Sinhala (Sri Lanka)' => 'si-LK',
            'Slovak (Slovakia)' => 'sk-SK',
            'Slovenian (Slovenia)' => 'sl-SI',
            'Somali (Somalia)' => 'so-SO',
            'Albanian (Albania)' => 'sq-AL',
            'Serbian (Latin, Serbia)' => 'sr-LATN-RS',
            'Serbian (Cyrillic, Serbia)' => 'sr-RS',
            'Sundanese (Indonesia)' => 'su-ID',
            'Swedish (Sweden)' => 'sv-SE',
            'Kiswahili (Kenya)' => 'sw-KE',
            'Kiswahili (Tanzania)' => 'sw-TZ',
            'Tamil (India)' => 'ta-IN',
            'Tamil (Sri Lanka)' => 'ta-LK',
            'Tamil (Malaysia)' => 'ta-MY',
            'Tamil (Singapore)' => 'ta-SG',
            'Telugu (India)' => 'te-IN',
            'Thai (Thailand)' => 'th-TH',
            'Turkish (Türkiye)' => 'tr-TR',
            'Ukrainian (Ukraine)' => 'uk-UA',
            'Urdu (India)' => 'ur-IN',
            'Urdu (Pakistan)' => 'ur-PK',
            'Uzbek (Latin, Uzbekistan)' => 'uz-UZ',
            'Vietnamese (Vietnam)' => 'vi-VN',
            'Chinese (Wu, Simplified)' => 'wuu-CN',
            'Chinese (Cantonese, Simplified)' => 'yue-CN',
            'Chinese (Mandarin, Simplified)' => 'zh-CN',
            'Chinese (Guangxi Accent Mandarin, Simplified)' => 'zh-CN-GUANGXI',
            'Chinese (Zhongyuan Mandarin Henan, Simplified)' => 'zh-CN-henan',
            'Chinese (Northeastern Mandarin, Simplified)' => 'zh-CN-liaoning',
            'Chinese (Zhongyuan Mandarin Shaanxi, Simplified)' => 'zh-CN-shaanxi',
            'Chinese (Jilu Mandarin, Simplified)' => 'zh-CN-shandong',
            'Chinese (Southwestern Mandarin, Simplified)' => 'zh-CN-sichuan',
            'Chinese (Cantonese, Traditional)' => 'zh-HK',
            'Chinese (Taiwanese Mandarin, Traditional)' => 'zh-TW',
            'isiZulu (South Africa)' => 'zu-ZA',
        ];

        foreach (['azure', 'frolax'] as $engine) {
            foreach ($languages as $name => $code) {
                TTSLanguage::create([
                    'code'       => $code,
                    'name'       => $name,
                    'enabled'    => true,
                    'engine'     => $engine,
                ]);
            }
        }
    }
}
