<?php

return [
    'acronyms' => [
        'id' => 'ID',
        'uuid' => 'UUID',
        'uid' => 'UID',
        'guid' => 'GUID',

        'url' => 'URL',
        'uri' => 'URI',
        'urn' => 'URN',
        'api' => 'API',
        'sdk' => 'SDK',
        'cli' => 'CLI',
        'ui' => 'UI',
        'ux' => 'UX',

        'ip' => 'IP',
        'ipv4' => 'IPv4',
        'ipv6' => 'IPv6',
        'dns' => 'DNS',
        'ssl' => 'SSL',
        'tls' => 'TLS',
        'ssh' => 'SSH',
        'ftp' => 'FTP',
        'sftp' => 'SFTP',
        'http' => 'HTTP',
        'https' => 'HTTPS',
        'smtp' => 'SMTP',
        'imap' => 'IMAP',
        'pop' => 'POP',
        'tcp' => 'TCP',
        'udp' => 'UDP',

        'html' => 'HTML',
        'css' => 'CSS',
        'js' => 'JS',
        'ts' => 'TS',
        'json' => 'JSON',
        'xml' => 'XML',
        'yaml' => 'YAML',
        'yml' => 'YAML',
        'csv' => 'CSV',
        'sql' => 'SQL',
        'nosql' => 'NoSQL',
        'graphql' => 'GraphQL',

        'db' => 'DB',
        'orm' => 'ORM',
        'crud' => 'CRUD',
        'jwt' => 'JWT',
        'oauth' => 'OAuth',
        'sso' => 'SSO',
        'mfa' => 'MFA',
        'otp' => 'OTP',
        'totp' => 'TOTP',
        'csrf' => 'CSRF',
        'xss' => 'XSS',
        'cors' => 'CORS',

        'seo' => 'SEO',
        'sem' => 'SEM',
        'crm' => 'CRM',
        'cms' => 'CMS',
        'erp' => 'ERP',
        'saas' => 'SaaS',
        'paas' => 'PaaS',
        'iaas' => 'IaaS',
        'b2b' => 'B2B',
        'b2c' => 'B2C',

        'ai' => 'AI',
        'ml' => 'ML',
        'llm' => 'LLM',
        'rag' => 'RAG',
        'nlp' => 'NLP',
        'ocr' => 'OCR',

        'pdf' => 'PDF',
        'png' => 'PNG',
        'jpg' => 'JPG',
        'jpeg' => 'JPEG',
        'svg' => 'SVG',
        'gif' => 'GIF',
        'webp' => 'WebP',

        'sms' => 'SMS',
        'mms' => 'MMS',
        'cdn' => 'CDN',
        'ci' => 'CI',
        'cd' => 'CD',
        'devops' => 'DevOps',

        'vat' => 'VAT',
        'tax' => 'Tax',
        'usd' => 'USD',
        'eur' => 'EUR',
        'gbp' => 'GBP',
        'bdt' => 'BDT',

        'pos' => 'POS',
        'sku' => 'SKU',
        'qr' => 'QR',
        'rfid' => 'RFID',

        'ios' => 'iOS',
        'macos' => 'macOS',
    ],
];
